<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260226212453 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        // $this->addSql('CREATE SCHEMA public');
        $this->addSql('CREATE TABLE pokemon (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, pokemon_id INT NOT NULL, nickname VARCHAR(32) NOT NULL, level INT NOT NULL, happiness INT NOT NULL, is_shiny BOOLEAN NOT NULL, gender VARCHAR(255) NOT NULL, ability VARCHAR(32) NOT NULL, nature VARCHAR(255) NOT NULL, held_item VARCHAR(64) NOT NULL, moveset_move1 VARCHAR(255) DEFAULT NULL, moveset_move2 VARCHAR(255) DEFAULT NULL, moveset_move3 VARCHAR(255) DEFAULT NULL, moveset_move4 VARCHAR(255) DEFAULT NULL, ivs_hp_iv INT NOT NULL, ivs_atk_iv INT NOT NULL, ivs_def_iv INT NOT NULL, ivs_sp_atk_iv INT NOT NULL, ivs_sp_def_iv INT NOT NULL, ivs_speed_iv INT NOT NULL, evs_hp_ev INT NOT NULL, evs_atk_ev INT NOT NULL, evs_def_ev INT NOT NULL, evs_sp_atk_ev INT NOT NULL, evs_sp_def_ev INT NOT NULL, evs_speed_ev INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE team (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C4E0A61FA76ED395 ON team (user_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_TEAM_USER_NAME ON team (user_id, name)');
        $this->addSql('CREATE TABLE team_pokemon (team_id INT NOT NULL, pokemon_id INT NOT NULL, PRIMARY KEY (team_id, pokemon_id))');
        $this->addSql('CREATE INDEX IDX_9DA5E1C4296CD8AE ON team_pokemon (team_id)');
        $this->addSql('CREATE INDEX IDX_9DA5E1C42FE71C3E ON team_pokemon (pokemon_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('CREATE TABLE user_pokemon (user_id INT NOT NULL, pokemon_id INT NOT NULL, PRIMARY KEY (user_id, pokemon_id))');
        $this->addSql('CREATE INDEX IDX_3AD18EF9A76ED395 ON user_pokemon (user_id)');
        $this->addSql('CREATE INDEX IDX_3AD18EF92FE71C3E ON user_pokemon (pokemon_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE team ADD CONSTRAINT FK_C4E0A61FA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE team_pokemon ADD CONSTRAINT FK_9DA5E1C4296CD8AE FOREIGN KEY (team_id) REFERENCES team (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE team_pokemon ADD CONSTRAINT FK_9DA5E1C42FE71C3E FOREIGN KEY (pokemon_id) REFERENCES pokemon (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_pokemon ADD CONSTRAINT FK_3AD18EF9A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_pokemon ADD CONSTRAINT FK_3AD18EF92FE71C3E FOREIGN KEY (pokemon_id) REFERENCES pokemon (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE team DROP CONSTRAINT FK_C4E0A61FA76ED395');
        $this->addSql('ALTER TABLE team_pokemon DROP CONSTRAINT FK_9DA5E1C4296CD8AE');
        $this->addSql('ALTER TABLE team_pokemon DROP CONSTRAINT FK_9DA5E1C42FE71C3E');
        $this->addSql('ALTER TABLE user_pokemon DROP CONSTRAINT FK_3AD18EF9A76ED395');
        $this->addSql('ALTER TABLE user_pokemon DROP CONSTRAINT FK_3AD18EF92FE71C3E');
        $this->addSql('DROP TABLE pokemon');
        $this->addSql('DROP TABLE team');
        $this->addSql('DROP TABLE team_pokemon');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE user_pokemon');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
